### ISSUE TITLE
Test card 1 added to In Progress list

### ISSUE THREAD

**Issue by JoeMeyerson** [mshanken/devmshanken#1]
<b>Joe Meyerson</b> added the card <a href="http://ift.tt/1MvWOHz">Test card 1</a> to the <b>In Progress</b> list in the <b>GitHub-Trello integration test</b> board at October 29, 2015 at 11:12AM<br><br><br><br><a href="http://ift.tt/1MvWOHz">View on Trello</a>

**Comment by mturro** [comment]
will do this as soon as hell freezes over.

**Comment by szhukov86** [comment]
Cartrello Anthony...

**Comment by mturro** [comment]
Serge... this is right up your alley

**Comment by szhukov86** [comment]
Cant see the card on trello but not sure that it matters?

![image](https://cloud.githubusercontent.com/assets/1035822/10823420/07b4c0c8-7e32-11e5-8b1e-227897d2e8e9.png)

**Comment by mturro** [comment]
you're not on that board so that makes sense.

**Comment by JoeMeyerson** [comment]
are now

On Thu, Oct 29, 2015 at 11:42 AM, Michael Turro notifications@github.com
wrote:

> you're not on that board so that makes sense.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mshanken/devmshanken/issues/1#issuecomment-152219828.

## 

Joe Meyerson
Director of Project Management
M. Shanken Communications, Inc.

**Comment by JoeMeyerson** [comment]
Closed due to age
