### ISSUE TITLE
Test card 2 added to In Progress list

### ISSUE THREAD

**Issue by JoeMeyerson** [mshanken/devmshanken#2]
<b>Joe Meyerson</b> added the card <a href="http://ift.tt/1KHUhm6">Test card 2</a> to the <b>In Progress</b> list in the <b>GitHub-Trello integration test</b> board at October 29, 2015 at 11:13AM<br><br><br><br><a href="http://ift.tt/1KHUhm6">View on Trello</a>

**Comment by JoeMeyerson** [comment]
Closed due to age

**Comment by szhukov86** [comment]
http://imagizer.imageshack.us/a/img922/8858/QEwt21.gif
